import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  login_bg: {
    flex: 1,
    resizeMode: 'stretch',
    justifyContent: 'center',
    alignItems: 'center',
  },
  parentContainer: {
    width: '91%',
    minHeight: '62%',
    backgroundColor: 'white',
    borderRadius: 12,
    borderColor: 'white',
    borderWidth: 1,
    alignItems: 'center',
  },
  logo: {
    marginTop: 24,
    width: 34,
    height: 34,
  },
  loginText: {
    marginTop: 24,
    fontSize: 32,
    fontFamily: 'Inter-Bold',
    includeFontPadding: false,
  },
  yourEmail: {
    marginTop: 12,
    fontSize: 12,
    fontFamily: 'Inter-Medium',
    includeFontPadding: false,
  },
  fnameTxt: {
    width: '82%',
    marginTop: 24,
    height: 48,
  },
  lnameTxt: {
    width: '82%',
    marginTop: 8,
    height: 48,
  },
  emailTextField: {
    width: '82%',
    marginTop: 24,
    height: 48,
  },
  emailPassword: {
    width: '82%',
    marginTop: 6,
    height: 48,
  },
  emailTextInput: {
    marginTop: 24,
    width: '82%',
    height: 48,
    backgroundColor: '#ffffff',
    borderRadius: 8,
    paddingLeft: 12,
    borderColor: '#EDF1F3',
    borderWidth: 1,
  },
  checkBoxContainer: {
    height: 20,
    width: '82%',
    marginTop: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  checkBoxView: {
    width: 106,
    height: '100%',
    flexDirection: 'row',
  },
  checkBoxBtn: {
    justifyContent: 'center',
    height: '100%',
  },
  checkBoxImg: {
    marginLeft: 4,
    marginBottom: 6,
    height: 12,
    width: 12,
    resizeMode: 'contain',
  },
  rememberMeText: {
    marginLeft: 6,
    fontSize: 12,
    fontFamily: 'Inter-Medium',
    color: '#6C7278',
    includeFontPadding: false,
  },
  forgotPassword: {
    marginLeft: 80,
    fontSize: 12,
    fontFamily: 'Inter-Bold',
    includeFontPadding: false,
    color: '#4D81E7',
  },
  loginBtn: {
    marginTop: 24,
    width: '82%',
    height: 48,
    backgroundColor: '#1D61E7',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loginTextBtn: {
    fontFamily: 'Inter-Medium',
    fontSize: 14,
    color: 'white',
    includeFontPadding: false,
  },
  orContainer: {
    height: 18,
    width: '82%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 16,
  },
  leftLine: {
    height: 0.5,
    width: '30%',
    backgroundColor: '#9b9191ff',
  },
  orWith: {
    fontFamily: 'Inter-Regular',
    fontSize: 12,
    color: '#6C7278',
    includeFontPadding: false,
  },
  socialIconsContainer: {
    height: 48,
    width: '82%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 24,
  },
  socialIcon: {
    height: 18,
    width: 18,
    resizeMode: 'contain',
  },
  socialIconBtn: {
    width: 62,
    height: 48,
    borderRadius: 10,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#EFF0F6',
  },
  dontHaveAccountContainer: {
    width: '82%',
    height: 17,
    marginTop: 24,
    marginBottom: 10,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  dontHaveAccountText: {
    fontFamily: 'Inter-Medium',
    fontSize: 12,
    color: '#6C7278',
    includeFontPadding: false,
  },
  signUpText: {
    fontFamily: 'Inter-Bold',
    fontSize: 12,
    color: '#4D81E7',
    marginLeft: 6,
    includeFontPadding: false,
  },
});
